### ISSUE TITLE
CephFS Shared volume creation question

### ISSUE THREAD

**Issue by hur** [dcplaya/home-ops#8818]
Hi, came across your repo from kubesearch - I'm trying to do a similar approach as you with Ceph SubVolumeGroups and shared volume creation.

I wanted to ask if you figured out a declarative approach to setting the credentials for the `rook-csi-cephfs-node-user` (i.e. `k8s/clusters/cluster-2/manifests/rook-ceph/cluster/secret.sops.yaml`) as the [rook guide](https://rook.io/docs/rook/latest-release/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/#shared-volume-creation) just instructs to copy the `rook-csi-cephfs-node` contents over to the new secret.

So I guess the question is if you've manually copied those credentials to the new secret or if you've figured out a nicer way to approach that - kind of stuck trying to make that declarative / avoid having to do that whenever provisioning a new cluster

EDIT: may have found a solution leveraging `CephClient` as the secrets generated seem to be of appropriate format. Testing this approach now.

Likely solved via 
```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: staticpvuser # corresponding secret: rook-ceph-client-staticpvuser
  namespace: rook-ceph
spec:
  caps:
    mgr: 'allow rw'
    mon: 'allow r fsname=ceph-filesystem'
    osd: 'allow rw tag cephfs metadata=ceph-filesystem, allow rw tag cephfs data=ceph-filesystem'
    mds: 'allow r fsname=ceph-filesystem path=/volumes, allow rws fsname=ceph-filesystem path=/volumes/media, allow rws fsname=ceph-filesystem path=/volumes/downloads'
```
